#!/bin/bash
set -euo pipefail

STAGED_CXX=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(c|cpp|cu|cuh|h)$' || true)

if [ -n "$STAGED_CXX" ]; then
    for file in $STAGED_CXX; do
        clang-format -i "$file"
        git add "$file"
    done
fi

STAGED_PY=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.py$' || true)

if [ -n "$STAGED_PY" ]; then
    black -q $STAGED_PY
    git add $STAGED_PY
fi
